
import { TipItem } from "../types";

export const ALL_TIPS: TipItem[] = [
  // TIGRINYA (30 TIPS)
  { cat: "TI", title: "Le son 'Q' éjectif", text: "Le Tigrinya possède des sons éjectifs comme le 'Q'. Contractez la gorge un court instant avant de relâcher l'air." },
  { cat: "TI", title: "Structure de phrase", text: "Le verbe se place presque toujours à la fin. Exemple : 'ኣነ ባኒ ይበልዕ' (Moi pain je mange)." },
  { cat: "TI", title: "Le respect (Nis'kum)", text: "Utilisez la forme plurielle 'Nis'kum' pour parler aux aînés ou au patron." },
  { cat: "TI", title: "Alphasyllabaire Ge'ez", text: "Chaque caractère contient une consonne et une voyelle. Il n'y a pas de lettres isolées." },
  { cat: "TI", title: "Doubles consonnes", text: "Appuyez fort sur les consonnes doublées (Gémination), cela peut changer le sens du mot." },
  { cat: "TI", title: "Salutations : Matin", text: "'Kemey hadir'kum' (Comment avez-vous passé la nuit ?) est la règle avant midi." },
  { cat: "TI", title: "Cérémonie du café", text: "Dire 'Buna t'um' (le café est délicieux) est un signe de politesse très apprécié." },
  { cat: "TI", title: "Négation", text: "Elle s'entoure de 'Ay' au début et 'n' à la fin. 'Ayfletun' = Je ne sais pas." },
  { cat: "TI", title: "Possessifs", text: "Ils sont suffixés : 'Seme-y' (Mon nom), 'Seme-ka' (Ton nom - masc), 'Seme-ki' (fem)." },
  { cat: "TI", title: "L'heure locale", text: "L'horloge commence à 6h du matin. Midi est donc la '6ème heure' du jour." },
  { cat: "TI", title: "Le son 'KH'", text: "Semblable à la 'jota' espagnole, c'est un son râpeux qui vient du fond de la gorge." },
  { cat: "TI", title: "Genre des objets", text: "Comme en français, les objets ont un genre (Masc/Fem). 'Shay' (thé) est masculin." },
  { cat: "TI", title: "Pluriel complexe", text: "Le pluriel change souvent l'intérieur du mot (Pluriel brisé), comme 'S'bah' -> 'Asebhti'." },
  { cat: "TI", title: "Nombres 1-10", text: "Hade, Kilete, Seleste, Arba'te, Hamushte, Shidish-te, Shebe'te, Shemonte, Tishe'te, 'Asherte." },
  { cat: "TI", title: "Manger l'Injera", text: "On mange toujours avec la main droite. C'est un code culturel strict." },
  { cat: "TI", title: "Particule 'do'", text: "Ajouter 'do' à la fin transforme une phrase en question. 'Yiserah do?' (Ça marche ?)." },
  { cat: "TI", title: "Impératif poli", text: "Pour demander poliment, on ajoute souvent 'bejakhum' (s'il vous plaît)." },
  { cat: "TI", title: "L'accent tonique", text: "L'accentuation est souvent sur la première ou l'avant-dernière syllabe." },
  { cat: "TI", title: "Prépositions", text: "Elles se soudent souvent au début du mot. 'Ab-bét' (Dans la maison)." },
  { cat: "TI", title: "Le son 'T' éjectif", text: "Prononcé en claquant la langue contre le palais sans laisser passer l'air." },
  { cat: "TI", title: "Dire 'Oui/Non'", text: "Oui = 'Uwe', Non = 'Aykonen' ou 'I-i'." },
  { cat: "TI", title: "Adverbes de temps", text: "'Lomi' (Aujourd'hui), 'Tsibah' (Demain), 'Timali' (Hier)." },
  { cat: "TI", title: "Langage corporel", text: "Lever légèrement les sourcils signifie souvent 'Oui' ou 'Je t'écoute'." },
  { cat: "TI", title: "Les couleurs", text: "Qeyih (Rouge), Tse'ada (Blanc), Tselim (Noir), Semayawi (Bleu)." },
  { cat: "TI", title: "Termes de parenté", text: "'Wedi' (Fils/Garçon), 'Gual' (Fille), 'Hafte' (Sœur), 'Hawe' (Frère)." },
  { cat: "TI", title: "Saisons", text: "Kiremti (Saison des pluies) est la période la plus importante pour l'agriculture." },
  { cat: "TI", title: "Météo", text: "Dites 'Tsubuq nifas alo' pour dire qu'il y a une bonne brise." },
  { cat: "TI", title: "Dire au revoir", text: "'Dehan wual' (Passe une bonne journée) ou 'Dehan hidar' (Bonne nuit)." },
  { cat: "TI", title: "Remerciements", text: "'Yeqenyeley' est le mot standard. Très formel : 'Teslem'." },
  { cat: "TI", title: "Excuses", text: "'Yiqreta' s'utilise aussi bien pour s'excuser que pour demander poliment de passer." },

  // FRANÇAIS (30 TIPS)
  { cat: "FR", title: "Les liaisons", text: "Prononcez le 'z' entre 'Les' et 'Amis'. C'est le secret d'un bon accent." },
  { cat: "FR", title: "Tu vs Vous", text: "Au travail, restez sur 'Vous' par défaut. C'est plus sécurisant et professionnel." },
  { cat: "FR", title: "Le 'E' final", text: "Ne le prononcez pas à la fin des mots. 'Table' s'arrête au son 'L'." },
  { cat: "FR", title: "Voyelles nasales", text: "Le son 'on' (ballon) se fait en faisant vibrer le nez. L'air ne sort pas par la bouche." },
  { cat: "FR", title: "Articles obligatoires", text: "On dit toujours 'LE bureau', jamais juste 'bureau'. L'article est nécessaire." },
  { cat: "FR", title: "Passé Composé", text: "Utilisez 'J'ai fini' pour une action terminée. C'est le temps du passé le plus utile." },
  { cat: "FR", title: "Accentuation", text: "La voix monte légèrement sur la toute dernière syllabe de la phrase." },
  { cat: "FR", title: "Espace et Ponctuation", text: "Mettez toujours un espace AVANT ':', '!' et '?'." },
  { cat: "FR", title: "Genre des mots", text: "Apprenez les mots avec leur genre (La porte, Le mur). C'est la base de la grammaire." },
  { cat: "FR", title: "Dire 'Bonjour'", text: "Indispensable en entrant dans un magasin ou un bureau. Sans ça, vous paraîtrez impoli." },
  { cat: "FR", title: "H aspiré", text: "Devant 'Haricot', on ne fait pas la liaison. On dit 'Les / haricots'." },
  { cat: "FR", title: "Du, De la (Partitifs)", text: "Utilisez-les pour une quantité inconnue. 'Je veux DU café' (une certaine quantité)." },
  { cat: "FR", title: "Ne...pas", text: "N'oubliez pas les deux parties de la négation à l'écrit. À l'oral, le 'ne' disparaît souvent." },
  { cat: "FR", title: "Le Futur Proche", text: "Utilisez 'Je vais + verbe' (Je vais manger). C'est très simple pour parler de demain." },
  { cat: "FR", title: "Conditionnel poli", text: "'Je voudrais' est beaucoup plus poli que 'Je veux'. À utiliser sans modération." },
  { cat: "FR", title: "L'imparfait", text: "C'est le temps des souvenirs. 'Quand j'étais petit...'. On l'utilise pour décrire." },
  { cat: "FR", title: "Subjonctif", text: "Utilisé après 'Il faut que...'. Exemple : 'Il faut que je parte'." },
  { cat: "FR", title: "Homophones", text: "Attention à 'et' (and) et 'est' (is). Ils se prononcent pareil mais n'ont rien à voir." },
  { cat: "FR", title: "Qui vs Que", text: "'Qui' est le sujet (L'homme qui rit), 'Que' est l'objet (Le livre que je lis)." },
  { cat: "FR", title: "À vs En", text: "On va 'À' Paris (ville), mais 'EN' France (pays féminin/commençant par voyelle)." },
  { cat: "FR", title: "Prononcer le 'R'", text: "Le son vient du fond de la gorge, comme si vous vous gargarisez légèrement." },
  { cat: "FR", title: "U vs OU", text: "'U' demande de faire une grimace (bisou), 'OU' est plus relâché (comme dans loup)." },
  { cat: "FR", title: "La Cédille (Ç)", text: "Elle permet au 'C' de sonner comme un 'S' devant 'a', 'o', 'u'. 'Garçon'." },
  { cat: "FR", title: "Accents", text: "L'accent aigu (é) est fermé, l'accent grave (è) est ouvert (comme dans forêt)." },
  { cat: "FR", title: "Exclamations", text: "'Zut !' ou 'Mince !' sont des façons polies de dire qu'on a fait une erreur." },
  { cat: "FR", title: "Faux-amis", text: "Une 'Librairie' vend des livres, une 'Bibliothèque' les prête gratuitement." },
  { cat: "FR", title: "L'heure (24h)", text: "En France, on utilise souvent le système 24h. 'Rendez-vous à 15h' (3pm)." },
  { cat: "FR", title: "Gastronomie", text: "Le repas est sacré. On reste souvent assis longtemps à table pour discuter." },
  { cat: "FR", title: "Lui / Leur", text: "Attention: 'Je lui parle' (à lui ou à elle). Le genre ne change pas ici." },
  { cat: "FR", title: "Expressions", text: "'C'est la vie' s'utilise quand quelque chose ne se passe pas comme prévu." },

  // ANGLAIS (30 TIPS)
  { cat: "EN", title: "Le son 'TH'", text: "Mettez la langue entre les dents. C'est bizarre au début mais indispensable pour 'The' ou 'Think'." },
  { cat: "EN", title: "Verbes irréguliers", text: "Les 50 verbes les plus fréquents sont souvent irréguliers. C'est le premier investissement à faire." },
  { cat: "EN", title: "Present Continuous", text: "Utilisez 'I am working' pour ce que vous faites à l'instant même." },
  { cat: "EN", title: "Word Stress", text: "Chaque mot long a une syllabe 'forte'. Si vous ne l'accentuez pas, on ne vous comprendra pas." },
  { cat: "EN", title: "Do / Does", text: "Utilisez 'Do' pour les questions simples. 'Do you like coffee?'." },
  { cat: "EN", title: "Phrasal Verbs", text: "Un petit mot après le verbe change tout. 'Pick' (choisir) vs 'Pick up' (ramasser)." },
  { cat: "EN", title: "Politesse (Could/Would)", text: "'Could you help me?' est bien meilleur que 'Help me'." },
  { cat: "EN", title: "Contractions", text: "Utilisez 'I'm', 'Don't', 'He's' pour avoir l'air naturel. Sans elles, vous paraîtrez trop formel." },
  { cat: "EN", title: "Adjectifs", text: "Ils se placent toujours AVANT le nom. 'A fast car', pas 'A car fast'." },
  { cat: "EN", title: "Mots de liaison", text: "'However', 'Therefore' aident à structurer vos mails pros." },
  { cat: "EN", title: "Lettres muettes", text: "Le 'K' dans 'Know' ou 'Knife' ne se prononce JAMAIS." },
  { cat: "EN", title: "Have vs Has", text: "N'oubliez pas le 'S' pour He/She/It. 'He HAS a car'." },
  { cat: "EN", title: "Articles (A/An)", text: "Utilisez 'AN' devant un son voyelle. 'An apple', 'An hour'." },
  { cat: "EN", title: "In, On, At (Temps)", text: "In (mois/année), On (jour précis), At (heure précise)." },
  { cat: "EN", title: "For vs Since", text: "'For' (durée : 2h), 'Since' (point de départ : 2010)." },
  { cat: "EN", title: "Voix Passive", text: "Très utilisée en entreprise pour paraître neutre. 'The report was sent'." },
  { cat: "EN", title: "Questions Wh-", text: "Who, What, Where, When, Why, How. Apprenez-les en priorité." },
  { cat: "EN", title: "Reported Speech", text: "Quand on rapporte les paroles de quelqu'un, le temps recule d'un cran (Is -> Was)." },
  { cat: "EN", title: "Ing vs To", text: "Certains verbes sont suivis de -ing (Enjoy swimming) et d'autres de to (Want to swim)." },
  { cat: "EN", title: "Conditionnels", text: "'If I win, I will...' (Possible) vs 'If I won, I would...' (Imaginaire)." },
  { cat: "EN", title: "Le 'S' final", text: "N'oubliez pas le 'S' à la 3ème personne du singulier au présent. 'She works'." },
  { cat: "EN", title: "Nombres Ordinaux", text: "Utilisez 'First, Second, Third' pour les dates, pas 'One, Two, Three'." },
  { cat: "EN", title: "Comparatifs", text: "'Faster' (court), 'More expensive' (long). Apprenez la règle du nombre de syllabes." },
  { cat: "EN", title: "Idiomes", text: "'A piece of cake' signifie que quelque chose est très facile." },
  { cat: "EN", title: "Emails Pros", text: "Commencez par 'Dear [Nom]' et finissez par 'Best regards' pour être pro." },
  { cat: "EN", title: "Voyelles longues", text: "Attention à la différence entre 'Ship' (court) et 'Sheep' (long)." },
  { cat: "EN", title: "Some vs Any", text: "'Some' pour les phrases positives, 'Any' pour les négations et questions." },
  { cat: "EN", title: "Modaux (Must/Can't)", text: "Utilisez-les pour exprimer une certitude. 'It must be him'." },
  { cat: "EN", title: "Which vs Who", text: "'Who' pour les personnes, 'Which' ou 'That' pour les objets." },
  { cat: "EN", title: "Small Talk", text: "Parler de la pluie et du beau temps est un passage obligé avant de parler business." }
];
